### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by oyeanuj** [rpearce/react-expanding-textarea#1]
Hi there! I was looking to try out our library but the demo link isn't working. Could you please take a look?

Thanks!

**Comment by rpearce** [comment]
Yeah! Sorry I just got this message

**Comment by rpearce** [comment]
I've updated the link on the repo to where it is now and also published 0.1.3 (removed some unused code):
http://rpearce.github.io/react-expanding-textarea/example/index.html

Let me know if you have any issues
