### ISSUE TITLE
The size should change when the textarea value is changed

### ISSUE THREAD

**Issue by thomassnielsen** [rpearce/react-expanding-textarea#10]
We're using react-expanding-textarea as an input field to a chat. We empty the textarea by setting value to an empty string on submit. This does not resize the textarea back to the initial size. 

Our current workaround is to save a ref to the component and call `this.textarea._adjustTextarea(this.textarea);`, which is not optimal and depends on an internal function not changing.

**Comment by thomassnielsen** [comment]
This is a simplified version of our code where I've stripped out all irrelevant code. In this case, when you submit and the textarea is emptied through the value being set to `''`, the textarea doesn't resize back to the original size.

```js
import Textarea from 'react-expanding-textarea';

class MessageForm extends Component {
  constructor(props) {
    super(props);
    this.state = { value: '' };

    this.handleSubmit = this.handleSubmit.bind(this);
    this.handleTyping = this.handleTyping.bind(this);
  }

  handleSubmit() {
    // submit data to the server, if successful:
    this.setState({ value: '' });
  }

  handleTyping(event) {
    this.setState({ value: event.target.value });
  }

  render() {
    return (
      <form onSubmit={this.handleSubmit}>
        <div>
          <Textarea
            rows="1"
            maxLength="10000"
            value={this.state.value}
            onChange={this.handleTyping}
          />
          <input type="submit" />
        </div>
      </form>
    );
  }
}

```

**Comment by rpearce** [comment]
@thomassnielsen thank you so much for providing this. I will make time for it within the next day or so and tag you and this issue on the pull request.

**Comment by rpearce** [comment]
@thomassnielsen I still haven't had a chance yet to get to this. Soon, I promise.

**Comment by thomassnielsen** [comment]
No worries! we’ve got a workaround for now, so nothing is on fire at our end. Thank you for your commitment!

**Comment by rpearce** [comment]
@thomassnielsen https://github.com/rpearce/react-expanding-textarea/pull/11 should fix your issue. I'll cut a release shortly

**Comment by rpearce** [comment]
@thomassnielsen upgrading to v`0.1.10` should solve your problem! If it doesn't, please let me know.

**Comment by thomassnielsen** [comment]
Perfect! I've tested this now and it works as expected. Thank you so much! I even learned something reading through your changes.
