### ISSUE TITLE
Take top/bottom border into account for sizing

### ISSUE THREAD

**Issue by jbsmith731** [rpearce/react-expanding-textarea#18]
I have a textarea with a 2px bottom border and it's not being taken into account when calculating the height. The input should be 40px tall but it's being calculated as 38px.

**Comment by rpearce** [comment]
@jbsmith731 Thanks for submitting your issue! Do you mind providing an example so I can debug using that? Looks like I'm just using `lineHeight`, `paddingBottom` and `paddingTop` at the moment, but it'd be useful to have something to test against.

**Comment by rpearce** [comment]
@jbsmith731 I'm almost done with a fix for this and am including it in a rewrite that uses react hooks. I'll check back here when I'm done!

If you need a fix that requires a React peer dependency < 16.8, let me know, and I can see about putting out a separate fix that doesn't require hooks.

**Comment by jbsmith731** [comment]
@rpearce thanks so much for checking back in. I've been so swamped I wasn't able to get back with an example. Thanks again for your hard work!

**Comment by rpearce** [comment]
@jbsmith731 This should now be available for use in version `1.0.0`, and note that this was included in a total rewrite that uses React hooks and has a peer dependency of React `>= 16.8`.

Thanks for the bug report, and you've been added to the All Contributors list: https://github.com/rpearce/react-expanding-textarea#contributors

**Comment by jbsmith731** [comment]
@rpearce this is awesome. Can't wait to check out the update! Thank you, sir!
