### ISSUE TITLE
Scrollbar is not taken into consideration

### ISSUE THREAD

**Issue by raunofreiberg** [rpearce/react-expanding-textarea#31]
Consider the example in http://rpearce.github.io/react-expanding-textarea/

The textarea grows in height, even though the text can still fit on one line.

![image](https://user-images.githubusercontent.com/23662329/66378639-9128bb80-e9bc-11e9-9888-a13fc2797e3e.png)

This happens because the textarea has a scrollbar on it, that is not shown because there isn't a max height on the textarea. It is possible to set `overflow: hidden` to make the textarea grow in height by not taking the scrollbar into consideration. Although, in this case, the scrollable functionality is lost.

**Comment by rpearce** [comment]
Interesting! Thank you for reporting this. What browser and operating system are you using?

**Comment by raunofreiberg** [comment]
OS: macOS Mojave 10.14.5 (18F132)
Browser: Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)

I took a look at other examples (e.g. https://andreypopp.com/react-textarea-autosize/) and the textarea only seems to grow when absolutely necessary.

Thanks!

**Comment by rpearce** [comment]
Thanks for the info!

Do you happen to also have scrollbars always on on your macOS or Chrome (if that's even an option)? I want to be sure I can recreate this

**Comment by raunofreiberg** [comment]
The scrollbars don't always appear, no. Does the example on `rpearce.github.io` reproduce for you?

**Comment by rpearce** [comment]
No, I don't see scrollbars at all in Chrome or Firefox on latest of each in latest macOS, and I don't see it grow when it doesn't need to.

Can you copy & paste the exact text you're using to recreate the issue?

**Comment by raunofreiberg** [comment]
![image](https://gyazo.com/0a75ce301274e56db89931a7ca76feba.gif)

I don't know if we're speaking about the same issue or not, but this is what I consider to be an issue. The textarea grows in size before actually needed (as you can see more text can fit on a single line when it does). Not sure if this is related to scrollbars or not?

**Comment by rpearce** [comment]
That's very interesting, indeed. Thank you for investigating that further. I'm away for the weekend at a work thing but can either hop on this when I'm back, or you can submit a PR!

**Comment by rpearce** [comment]
Your fix should now be in `v2.0.3`!

Welcome to the contributors list, too!
<img width="359" alt="image" src="https://user-images.githubusercontent.com/592876/66789861-fe68af00-eedc-11e9-897d-5b3037dfa5ff.png">
