### ISSUE TITLE
Exposing ref

### ISSUE THREAD

**Issue by tknuts** [rpearce/react-expanding-textarea#36]
We need to be able to access "ref" on the textarea to be able to set focues() on the textarea from the parent. 

Or you could expose a "SetFocus" prop :-)

**Comment by rpearce** [comment]
I can consider [forwarding a ref](https://reactjs.org/docs/forwarding-refs.html), but I'm not :100: sure I want to do that (hooks don't generally like it when you make them conditional).

I'll come up with something but just need a little time to think about it!

**Comment by rpearce** [comment]
@tknuts This should be resolved by #37 and is published in version `2.1.1`.

I have also added you to the [All Contributors list](https://github.com/rpearce/react-expanding-textarea#contributors)! Thank you for your contribution to this project.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/592876/72694766-0fedd280-3b2e-11ea-9670-36cb713155f1.png">

**Comment by ghert** [comment]
@rpearce 
Can you release new version?

**Comment by rpearce** [comment]
@ghert That was a typo above; I meant `2.1.0`. Here is the line in the CHANGELOG in the PR that added this functionality: https://github.com/rpearce/react-expanding-textarea/pull/37/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR10

Sorry for the confusion!
