### ISSUE TITLE
don't expand if value does not change based on input

### ISSUE THREAD

**Issue by chrisdrackett** [rpearce/react-expanding-textarea#39]
I'm trying to create a text area that will resize if it overflows, but submits when the user presses enter. I'm trying the following code:

```js
<Textarea
  value={props.value}
  onInput={({target: { value: text }}) => {
    if (text.substr(text.length - 1, 1) === '\n') {
      console.log('submit function here!')
    } else {
      onInput(text)
    }
  }
/>
```

this is mostly working, however I'm running into an issue where the text area will grow when I press `enter`.

**Comment by rpearce** [comment]
Hello, and thank you for using this and asking a question!

I believe that `enter`/`return` in a regular browser `<textarea>` has the same functionality as this; pressing `enter` will result in a newline, so this is expected. You can view this here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea.

This component is built around the notion that it should be an expanding `<textarea>`, so limiting its default capabilities, so I'm not sure we want to limit that.

**Comment by chrisdrackett** [comment]
No worries, I was able to get this myself by preventing default on keydown when the key is an enter key.

My use-case is that I want a single line field (no new lines) that instead of expanding horizontally expands vertically so the user can still read all the text. I’m good to go using the keydown event!
