### ISSUE TITLE
Issue testing with enzyme

### ISSUE THREAD

**Issue by lloydwatkin** [rpearce/react-expanding-textarea#4]
Issue is here https://github.com/rpearce/react-expanding-textarea/blob/master/src/ExpandingTextarea.js#L20-L21

In tests if you do something like:

```javascript
_component.find(Textarea).simulate('change', { target: { value: '1.21 gigawatts?!?' } })
```

Error message returned is '_Attempted to assign to readonly property_' (techincally these properties should be read only https://developer.mozilla.org/en-US/docs/Web/API/Event, but obviously that isn't happening in browsers since the property is mutable.

I did have a short term hack which was
```javascript
  component.find(Textarea).simulate('change', { hack: '1.21 gigawatts?!?' })
```
and then in my `onChange` I referenced the textarea's value as such:

```javascript
const body = event.target.value || event.hack
```

However, I've found a nicer work around. Enzyme merges that data value into the event object, so we can overwrite the **style** property as such:
```javascript
  component.find(Textarea).simulate(
    'change',
    { target: { value: '1.21 gigawatts?!?', style: {} } }
  )
```

Which works just great! Might be something for the README :)

**Comment by rpearce** [comment]
I find GH Issues themselves to be good documentation of issues & workarounds people have found – they help my colleagues and I immensely every few days! Thank you for writing this all out, and it will help someone in the future, no doubt.
