### ISSUE TITLE
maxHeight no scrollbar

### ISSUE THREAD

**Issue by 1v** [rpearce/react-expanding-textarea#43]
When adding `maxHeight` and text has many lines - scroll bar in textarea is not appears because `overflow-y: hidden;` added to textarea.

**Comment by rpearce** [comment]
@1v can you please provide a project demo that demonstrates this issue? That would be very helpful!

**Comment by rpearce** [comment]
@elitenoire thank you for walking me through exactly how to reproduce the issue. I'll see what I can do

**Comment by rpearce** [comment]
I started looking into this and didn't see a quick solution; I apologize for the delay. I've been working extensively on https://github.com/rpearce/image-zoom/pull/244 in my spare time and haven't made time for this yet.

If anybody cares to open a PR that fixes this and does not regress other issues, that would definitely speed this along!

**Comment by chrisdrackett** [comment]
running into something similar but the height is handed outside of the `textarea` I might have time to take a look at both tomorrow

**Comment by rpearce** [comment]
Any help is appreciated!

**Comment by rpearce** [comment]
@chrisdrackett did you find a solution to this that you could share?

**Comment by rpearce** [comment]
@1v @elitenoire @chrisdrackett This should be resolved in `v2.2.3`, and you can check it out here: https://rpearce.github.io/react-expanding-textarea/?path=/story/expandingtextarea--with-max-height.

If you have any more issues with this, I will reopen the issue.

Thank you all for your contributions by reporting this! I've added you to the all contributors list in the README.
