### ISSUE TITLE
Cannot use with typescript

### ISSUE THREAD

**Issue by markathomas** [rpearce/react-expanding-textarea#47]
Attempting to use with typescript via the following declaration:
```
import * as React from 'react';
import Textarea from 'react-expanding-textarea';

                        <Textarea
                            name='statement'
                            value={this.state.statement}
                            onChange={this.handleChange}
                            margin="normal"
                            variant="outlined"
                            required={false}
                            style={{ width: '100%' }}
                        />
```

and receiving the following error:

`TS2339: Property 'name' does not exist on type 'IntrinsicAttributes & TextareaProps & RefAttributes '.`

**Comment by rpearce** [comment]
Hi! I'm sorry you're experiencing a problem :(

Based on https://github.com/rpearce/react-expanding-textarea/blob/master/source/index.tsx#L51-L58, would you know off the top of your head what the problem is? I can't look at this until the weekend. Do I need to export that interface? 🤔

**Comment by markathomas** [comment]
I'm not sure

**Comment by rpearce** [comment]
Okay. I haven't gotten to this yet, but it's on my to-do list.

**Comment by rpearce** [comment]
@markathomas I'll get to this in the next couple of days. Thanks for your patience.

**Comment by rpearce** [comment]
@markathomas can you try version `2.2.2`?
