### ISSUE TITLE
Utilise prop-types package instead of React.PropTypes

### ISSUE THREAD

**Issue by jch254** [rpearce/react-expanding-textarea#5]
Hi, great work with this package. Unfortunately I am unable to use with React 16 as PropTypes is no longer included as part of React. The solution is to utilise the [prop-types package](https://github.com/facebook/prop-types).

Cheers

**Comment by rpearce** [comment]
@jch254 thank you for reporting this! I should have done this ages ago. I'll put it on my to-do list and get to it in the next day or so. If you need it ASAP, let me know, and I'll shift my schedule around a bit to help you out.

**Comment by jch254** [comment]
Awesome cheers @rpearce! I'm in no hurry so take your time 👍

**Comment by rpearce** [comment]
@jch254 can you give https://github.com/rpearce/react-expanding-textarea/pull/7 some 👀 ? Should be good to go. If so, I'll merge and publish `v0.1.9`

**Comment by jch254** [comment]
Brilliant good stuff thxagain

**Comment by rpearce** [comment]
@jch254 This is now published under `v0.1.9`
