### ISSUE TITLE
Github Pages demo page is not available

### ISSUE THREAD

**Issue by VitalyKrenel** [rpearce/react-expanding-textarea#53]
Hey folks!

Right now, the demo page is not available: https://rpearce.github.io/react-expanding-textarea/
![image](https://user-images.githubusercontent.com/17354709/100540676-bd9e3780-324f-11eb-9cf7-f151475b873c.png)

Might be that after switching from `master` branch to `main` the Github Pages was not updated to point to `main` as well.

**Comment by VitalyKrenel** [comment]
CC: @rpearce @raunofreiberg

**Comment by rpearce** [comment]
Thanks! You were absolutely right. It's published now.
