### ISSUE TITLE
onsubmit functionality

### ISSUE THREAD

**Issue by visgotti** [rpearce/react-expanding-textarea#6]
Any chance you can add an onSubmit so when pressing enter it fires off

**Comment by rpearce** [comment]
@visgotti I believe pressing return/enter inside of a `<textarea>` creates new lines and does not submit a form, thus this request might not make sense. However, any props you pass to the component will be set as props on the textarea (think `onInput` or `onKeyUp`). For your use case, you could use `onKeyUp`, check if the key code is the one for return/enter, then submit your form yourself.

**Comment by visgotti** [comment]
Yeah that's actually pretty much what I winded up doing. Just used onKeyUp and then check the key code.
