### ISSUE TITLE
Allow updating of textarea height on initial render

### ISSUE THREAD

**Issue by simonsmith** [rpearce/react-expanding-textarea#60]
Hey,

I'm building a feature where I restore text to the textarea from `sessionStorage` on render and I note that it doesn't update the height when I refresh the page and set the value:

![2021-06-14 10 36 32](https://user-images.githubusercontent.com/360703/121874694-81b85480-ccff-11eb-9aad-a53ff804530f.gif)

Could the textarea detect this on initial render or perhaps provide an API for this? 

Cheers!

**Comment by rpearce** [comment]
@simonsmith Thank you for using this and submitting this issue! Could you share a code example (a demo repository would be :100:) of how you're using this so that I can easily reproduce it and address this faster?

**Comment by rpearce** [comment]
@simonsmith were you able to figure something out?

**Comment by simonsmith** [comment]
Hey, sorry for lack of reply. When I looked into it I couldn't replicate with just this library. I think it could be my setup with react-hook-form. It's quite a lot to unpick from the app I'm using it in which is why I got sidetracked.

I'll close this for now and if I find a concrete way to replicate I'll come back :)
