### ISSUE TITLE
Textarea does not automatically recalculate size if it's parent container changes size

### ISSUE THREAD

**Issue by jamesmoss** [rpearce/react-expanding-textarea#71]
If the textarea is 100% width and it's parent container changes size, the height of the text area is not re-calculated.

I've put together an example here https://codesandbox.io/s/cool-estrela-7wq7f?file=/src/App.js

By toggling the textarea to the wider size, there's loads of whitespace below the last line, once you focus in the field and start typing this gets correctly removed.

This needs to use `ResizeObserver` to monitor for changes to the size of the textarea.

**Comment by jamesmoss** [comment]
I've realised that there's also a similar issue if you change how the content inside the textarea looks, e.g changing font size through a style tag or adding a new css classname.  A new `useEffect` for both of those is needed to call `resize`

If you feel like tackling both these issues in this library is overkill then it'd be nice if the `resize` function was exposed somehow so we could add our own implementation and force a resize recalculation whenever we wanted.

**Comment by rpearce** [comment]
These are good callouts and ideas. I'll think about these this week and follow up

**Comment by rpearce** [comment]
I fiddled with this diff for a few minutes:

```diff
diff --git a/source/index.tsx b/source/index.tsx
index 96f398a..9e8791c 100644
--- a/source/index.tsx
+++ b/source/index.tsx
@@ -5,7 +5,7 @@ import React, {
   RefObject,
   TextareaHTMLAttributes,
   useCallback,
-  useEffect,
+  useLayoutEffect,
   useRef,
 } from 'react'
 import withForwardedRef from 'react-with-forwarded-ref'
@@ -82,7 +82,19 @@ const ExpandingTextarea: FC<TextareaProps> = ({
   const rows = props.rows ? parseInt('' + props.rows, 10) : 0
   const { onChange, onInput } = props
 
-  useEffect(() => {
+  useLayoutEffect(() => {
+    const observer = new ResizeObserver(() => {
+      resize(rows, ref.current)
+    })
+
+    observer.observe(ref.current)
+
+    return () => {
+      observer.disconnect()
+    }
+  }, [ref, rows])
+
+  useLayoutEffect(() => {
     resize(rows, ref.current)
   }, [ref, rows, props.value])
```

The container resizing seems good, but font size changing still needs work. I'll ponder it in my spare time.

**Comment by jamesmoss** [comment]
We're currently migrating from a crappy old jquery library and we used `MutationObserver` which works for our single use case but isnt pretty:

```
let lastFontSize = null;

this.mo = new MutationObserver((mutations) => {
  mutations.forEach((mutation) => {
    if (
      mutation.type === 'attributes' &&
      mutation.attributeName === 'style'
    ) {
      if (mutation.target.style.fontSize !== lastFontSize) {
        lastFontSize = mutation.target.style.fontSize;
        // Code here to recalculate size
      }
    }
  });
});

this.mo.observe(element, {
  attributes: true,
  attributeOldValue: true,
});
```

This is why I think recalculating on `style` and `className` props changing would make more sense, it won't cover all cases (e.g cascading styles from the parent changing styles/classes) but should get many and is way nicer than using `MutationObserver`

On that note, both of the observers aren't supported in IE11 and some really old evergreen browser versions, it's probably worth adding a check to see if they exist before using them.

**Comment by rpearce** [comment]
All of those are good recommendations, and if we were to include those, I would 💯 do that for checking if they exist.

Here's another thought: perhaps I could measure the scroll height of the textarea from one render to the next, and if that changes, recalculate? What would that not cover?

**Comment by jamesmoss** [comment]
I dont think you could listen for changes to that in the DOM with `MutationObserver` so wouldn't cover this case.

**Comment by rpearce** [comment]
@jamesmoss Good point

**Comment by jamesmoss** [comment]
I've been thinking on this more this evening and doing some more research; I don't think there's a clean, performant way to listen for computed style changes until they invent a `StyleObserver`.  However, I'd love to be proven wrong here.

Right now I think the strategy using `ResizeObserver` for size changes and `useLayoutEffect` on `className` and `style` prop changes would be a best effort approach (and skips the complexity of `MutationObserver`). It won't catch font size/family/line-height changes made to any parent elements but I think that's an okay trade-off for simplicity.

**Comment by rpearce** [comment]
Looks like I'm already exporting `resize`, and it accepts `(rows: number, el: HTMLTextAreaElement | null)`, so that's a plus.

How does this changeset strike you for the rest?

```diff
diff --git a/source/index.tsx b/source/index.tsx
index b36ebbb..5e2d85f 100644
--- a/source/index.tsx
+++ b/source/index.tsx
@@ -6,6 +6,7 @@ import React, {
   TextareaHTMLAttributes,
   useCallback,
   useEffect,
+  useLayoutEffect,
   useRef,
 } from 'react'
 import withForwardedRef from 'react-with-forwarded-ref'
@@ -82,9 +83,25 @@ const ExpandingTextarea: FC<TextareaProps> = ({
   const rows = props.rows ? parseInt('' + props.rows, 10) : 0
   const { onChange, onInput, ...rest } = props
 
+  useEffect(() => {
+    if (!window.ResizeObserver) {
+      return
+    }
+
+    const observer = new ResizeObserver(() => {
+      resize(rows, ref.current)
+    })
+
+    observer.observe(ref.current)
+
+    return () => {
+      observer?.disconnect()
+    }
+  }, [ref, rows])
+
   useEffect(() => {
     resize(rows, ref.current)
-  }, [ref, rows, props.value])
+  }, [props.className, props.style, props.value, ref, rows])
 
   const handleInput = useCallback(
     (e) => {
```

**Comment by jamesmoss** [comment]
Couple of things I can see:

1. `className` can also be an object (which has a `toString` method), many people use helpers like https://github.com/JedWatson/classnames lots (including our team). To prevent unnecessary resizes you should do something like `className?.toString()` in the dependencies array otherwise you'd have a fresh object each render and `useLayoutEffect` will always be called. 
2. In a similar vein, `style` will be an object and many people won't be memoizing it before passing it just doing something like `<Textarea style={{ fontSize: 24 }} />`. Again this will cause unnecessary calls of `useLayoutEffect`, you could use something like `object-hash` to turn the style prop into a hash that is then used in the dependency array.

You could also ignore both of these suggestions if you think the resizing calculation is fast enough and don't mind it being called too many times.

**Comment by jamesmoss** [comment]
Yeah you're totally right about `classnames`, ignore my comment there then. Agreed that `object-hash` is pretty heavy, since `styles` is only ever a one level deep map maybe there's something more simple that can be implemented.

**Comment by rpearce** [comment]
Will look at https://github.com/streamich/fast-shallow-equal/blob/master/index.js later

**Comment by rpearce** [comment]
I'm honestly exhausted, and I need to actually test this (Storybook), but here's a commit of attempting to shallow compare a `style` prop efficiently: https://github.com/rpearce/react-expanding-textarea/pull/78/commits/e2e891e0ccf281c5788696ececed25c75dcaf375

**Comment by jamesmoss** [comment]
@rpearce Sorry for lack of input, I've been away over the Christmas break. 

I had a look at your implementation, I'm sure you'd agree it looks pretty complex with the usage of refs.

How about instead of using `fast-shallow-equal` just write our own simple style hash function? I took a look at the types for `React.CSSProperties`, we can assume that the styles are effectively a shape of `Record<string, string | number>`. With that in mind I wrote this simple style hash function which can be passed into the dependencies array of `useLayoutEffect`.

https://codesandbox.io/s/optimistic-tharp-1yhq0?file=/src/index.tsx

It takes the keys and values of the styles and just joins them all together. I feel like this should cover most use cases right now. The only downside is that it relies on `Object.entries` and `Array.flat` which aren't supported in IE11, I'm sure most people are polyfilling them already for that environment, but worth making clear in the readme. You could also convert my implementation to ES5 pretty easily.

Also wanted to say thanks for your efforts so far on this!

**Comment by rpearce** [comment]
@jamesmoss Could you take a look at https://github.com/rpearce/react-expanding-textarea/pull/78 when you get some time?

**Comment by rpearce** [comment]
> I had a look at your implementation, I'm sure you'd agree it looks pretty complex with the usage of refs.

I've updated this by pulling the logic into a custom, memoized-object-returning hook.

* * *

I'll think a bit more about the hashing / object checking. This lib still looks pretty good to me, but I need to think about the other options and their tradeoffs:

https://github.com/streamich/fast-shallow-equal/blob/fa68eb5a86cc0206191c165503338947e4eed9d3/index.js#L1-L17

**Comment by rpearce** [comment]
I've done a bit of reading and comparing of implementations, and I think that tiny lib implementation combined with this feel good to me. Doing this in an ES5-ish-friendly manner to turn it into a string feels like a lot of strings getting created in memory, but then again, it would probably be negligible.

If there's any issue with this, I'm happy to circle back. I'm going to go ahead and cut a release with this.

**Comment by jamesmoss** [comment]
Hey, just wanted to say thank you so much for this. This definitely feels like the most robust react based expanding textarea lib I've come across now.

**Comment by rpearce** [comment]
It only can be with help from good folx like you! I appreciate your investment here.
