### ISSUE TITLE
Use useLayoutEffect instead of useEffect

### ISSUE THREAD

**Issue by jamesmoss** [rpearce/react-expanding-textarea#72]
This change will prevent some flickering that I've seen, Kent describes it well here https://kentcdodds.com/blog/useeffect-vs-uselayouteffect:

> However, if your effect is mutating the DOM (via a DOM node ref) and the DOM mutation will change the appearance of the DOM node between the time that it is rendered and your effect mutates it, then you don't want to use useEffect. You'll want to use useLayoutEffect. Otherwise the user could see a flicker when your DOM mutations take effect.

I'd say this is the perfect use case.

**Comment by rpearce** [comment]
@jamesmoss Thank you for bringing this up. I'll try it out with this and see how it goes

**Comment by rpearce** [comment]
Checks out! I've got this queued up for the next patch-level release, and I've added you to the all contributors list in the README! Thanks for your time here.
